# Site settings
url: "https://acrand06.github.io" # your host, for absolute URL
baseurl: "/sweet-solutions" # for example, '/blog' if your blog hosted on 'host/blog'
title: "Sweet Solutions for z/OS Modernization "
SEOTitle: "Solutions for z/OS Modernization"
header-img: img/home-bg.png
email: acrand@us.ibm.com
description: "Anthony's solutions for moderniztionation journey for z/OS"
keyword: "Computers, Tech, Compilers, z/OS, Open Source"

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: acrand06
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: sweet-solutions

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: G-4LCKQVYR6Q # "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: acrand06.github.io # huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Anthony Randolph - Solutions Enablment Lead for IBM Z and Cloud Modernization Stack"
sidebar-avatar: https://github.com/acrand06.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "Mike Fulton's Blog", href: "https://makingdeveloperslivesbetter.wordpress.com/" },
    { title: "Igor Todorovski's Blog", href: "https://igortodorovskiibm.github.io/blog/" },
    { title: "Latrell Freemans's Blog", href: "https://freemanlatrell.github.io/blog/" }
  ]

